const posts = [
	{
		id: 1,
		title: 'Yorch',
		content: 'admin@admin.com',
        avatar:'../assets/defaultavatar.jpg',
        userId: undefined,		      
	},
	// {
	// 	id: 2,
	// 	title: 'Obi Wan Kenobi',
	// 	content: 'lasthope@email.com',
    //     avatar:'../assets/defaultavatar.jpg',
    //     userId: {type: ObjectId, ref: 'User'},		
	// },
	// {
	// 	id: 3,
	// 	title: 'Rey Skywalker',
	// 	content: 'sucks@sucks.com',
    //     avatar:'../assets/defaultavatar.jpg',
    //     userId: {type: ObjectId, ref: 'User'},		
	// },
	// {
	// 	id: 4,
	// 	title: 'John Don',
	// 	content: 'John@John.com',
    //     avatar:'../assets/defaultavatar.jpg',
    //     userId: {type: ObjectId, ref: 'User'},
	// },
    // {
	// 	id: 5,
	// 	title: 'John Don',
	// 	content: 'John@John.com',
    //     avatar:'../assets/defaultavatar.jpg',
    //     userId: {type: ObjectId, ref: 'User'},
	// },
    // {
	// 	id: 6,
	// 	title: 'John Don',
	// 	content: 'John@John.com',
    //     avatar:'../assets/defaultavatar.jpg',
    //     userId: {type: ObjectId, ref: 'User'},
	// },
    // {
	// 	id: 7,
	// 	title: 'John Don',
	// 	content: 'John@John.com',
    //     avatar:'../assets/defaultavatar.jpg',
    //     userId: {type: ObjectId, ref: 'User'},
	// },
    // {
	// 	id: 8,
	// 	title: 'John Don',
	// 	content: 'John@John.com',
    //     avatar:'../assets/defaultavatar.jpg',
    //     userId: {type: ObjectId, ref: 'User'},
	// },
    // {
	// 	id: 9,
	// 	title: 'John Don',
	// 	content: 'John@John.com',
    //     avatar:'../assets/defaultavatar.jpg',
    //     userId: {type: ObjectId, ref: 'User'},
	// },
    // {
	// 	id: 10,
	// 	title: 'John Don',
	// 	content: 'John@John.com',
    //     avatar:'../assets/defaultavatar.jpg',
    //     userId: {type: ObjectId, ref: 'User'},
	// },
    // {
	// 	id: 11,
	// 	title: 'John Don',
	// 	content: 'John@John.com',
    //     avatar:'../assets/defaultavatar.jpg',
    //     userId: {type: ObjectId, ref: 'User'},
	// },
    // {
	// 	id: 12,
	// 	title: 'John Don',
	// 	content: 'John@John.com',
    //     avatar:'../assets/defaultavatar.jpg',
    //     userId: {type: ObjectId, ref: 'User'},
	// },
    // {
	// 	id: 13,
	// 	title: 'John Don',
	// 	content: 'John@John.com',
    //     avatar:'../assets/defaultavatar.jpg',
    //     userId: {type: ObjectId, ref: 'User'},
	// },
    // {
	// 	id: 14,
	// 	title: 'John Don',
	// 	content: 'John@John.com',
    //     avatar:'../assets/defaultavatar.jpg',
    //     userId: {type: ObjectId, ref: 'User'},
	// },
];

module.exports = posts;